### PR TITLE
[ANA-4338]: Add darwin support

### PR DESCRIPTION
**Pull request by subham-deepsource**
Changeset includes shared libraries for Mac OSX so that murdock supports on the same. Also fixed extension and naming conventions for platform-dependent shared libraries: `.so` (linux), `.dylib` (darwin), `.dll` (windows).

For Linux and Darwin: `libfoo.{so,dylib}`
For Windows: `foo.dll` (made an exception by not removing the preceding `_` for `_gomod.dll`)

Also, fixed some nitpicks and directory names.

Signed-off-by: subham sarkar <subham@deepsource.io>

### CODE REVIEW

**Comment by subham-deepsource** [comment]
@tushar-deepsource Give it a try and let me know if it works?

**Review by tushar-deepsource — APPROVED** [review]

**Comment by shmsr** [comment]
@NobleMathews @srijan-deepsource Please review?

**Review by NobleMathews — APPROVED** [review]
Built for Windows and Linux. Added fixes for failing test and missed key refactoring in the python part.

**Comment by subham-deepsource** [comment]
> Built for Windows and Linux. Added fixes for failing test and missed key refactoring in the python part.

Thanks, @NobleMathews!

**Pull request merged**
